[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "Command_Line_File_Manager"
version = "0.1.0"
description = ""
readme = "README.md"
authors = [
    { name = "Kaloyan Ivanov", email = "kaloyan.ivanov88@gmail.com" }
]

requires-python = ">=3.8"

dependencies = [
    "black == 23.9.1",
    "cachetools == 5.3.1",
    "chardet == 5.2.0",
    "click == 8.1.7",
    "codespell == 2.2.6",
    "colorama == 0.4.6",
    "directory-tree == 0.0.4",
    "distlib == 0.3.7",
    "emoji == 2.8.0",
    "filelock == 3.12.4",
    "mypy-extensions == 1.0.0",
    "packaging == 23.2",
    "pathspec == 0.11.2",
    "platformdirs == 3.11.0",
    "pluggy == 1.3.0",
    "pyproject-api == 1.6.1",
    "tox == 4.11.3",
    "virtualenv == 20.24.5",
]

[project.scripts]
fm = "app.__main__:cli"
